---
title: "GSVA analysis for mutil Group" 
subtitle: ""
author: "Ximing Ran"
date: "2025-03-31"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: false
  html_document:
    # code_folding: hide
    toc: true
    toc_float: true
hitheme: tomorrow
highlighter: highlight.js

---

```{r setup, include=FALSE}
# load libraries
library(tidyverse)
library(knitr)
set.seed(2024)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.path = "./results/03-GSVA/Analysis_figure/"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
knitr::kable(head(mtcars[, 1:4]), "simple")
```

```{r}
library(tibble)
library(tidyr)
library(dplyr)
library(rtracklayer)
```



```{r local_function_load}
# load function from local files
source(here::here("source", "DEG_functions.R"))
```

\newpage

# 1. Read the count data
In this section, we will read the clean count data from the synaptosomes_bulkRNA folder.  We will read the data and merge them into a single table. The final table will be stored in `results/02-DEG-Vehicle/synaptosomes_bulkRNA_counts_clean.csv`.

```{r load_bulkRNA_data}
input_count <- read.csv(here::here("data", "synaptosomes_bulkRNA",
                                      "synaptosomes_bulkRNA_counts_cleaned.csv"))
counts <-  as.data.frame(input_count) %>% 
  column_to_rownames(var = "gene")
colnames(counts) <- gsub("_", "-", colnames(counts))


# raw sample list
sample_list_raw <- read.csv(here::here("data", "synaptosomes_bulkRNA",
                                      "sample_info_22q.csv")) %>%
                    mutate(condition = paste0(Diagosis, "_", Treatment))


# Ensure the column names of counts exist in Sample.name
new_colnames <- sample_list_raw$Label[match(colnames(counts), sample_list_raw$Sample.name)]

# Assign new column names
colnames(counts) <- new_colnames


# sort the columns by the colname
condition_list <- data.frame(
  group =sample_list_raw$condition
)

row.names(condition_list) <- sample_list_raw$Label

counts<- counts[, rownames(condition_list)]

# load the 22q gene_list
target_22q_gene <- read.csv(here::here("data","ref" ,"22q_gene_2024_10_17.csv"))
target_gene <- target_22q_gene$gene
target_gene <- target_gene[1:(length(target_gene) - 4)]

gene_name_mapping<- readRDS(here::here("data","ref" ,"gene_name_mapping.rds"))




```



# 2. GSVA analysis

```{r GSVA_analysis, fig.width=4, fig.height=6}
result_folder = "results"

# gmxFile <- here::here("data", "ref", "c5.go.v2023.1.Hs.symbols.gmt")
# go_list <- getGmt(gmxFile)
# 
# geneset <- go_list
# dat <- as.matrix(counts)
# 
# gsvapar <- gsvaParam(dat, geneset, maxDiff=TRUE)
# gsva_es <- gsva(gsvapar)
# gsva_matrix <- as.data.frame(gsva_es)
# 
# # save the result
# write.csv(gsva_matrix, file.path("results","03-GSVA", "01_GSVA_matrix.csv"))
# 
# 



gsva_matrix <- read.csv(file.path("results","03-GSVA", "01_GSVA_matrix.csv"),
                        row.names = 1)
colnames(gsva_matrix) <-sub("^X", "", colnames(gsva_matrix))
condition_list_label <- condition_list %>%
  mutate(group = str_replace_all(group, "_", "+"),
         group = str_replace_all(group, "Vehicle", "Veh"))

  

# plot the heatmap for the GSVA result
pathway_list <- read.csv(here::here("data", "ref", "focus-pathway_2024_10_03.csv"))


# # plot for all pathway
# for (i in 1:nrow(pathway_list)){
#   if (i %% 10 == 0) print(i)
#   pathway_name <- pathway_list$pathway[i]
#   plot_gsva_boxplot_4_group(gsva_matrix,
#                           condition_list_label =condition_list_label,
#                           pathway_name =  pathway_name,
#                           figure_folder = file.path(result_folder,"03-GSVA","Boxplot"),
#                           file_name = paste0("GSVA_", pathway_name),
#                           fig.height = 6, fig.width = 4,
#                           save=TRUE,
#                           group_1="CTRL+Veh", group_2="22q+Veh",
#                           group_3="CTRL+TTX", group_4="22q+TTX")
# }


# plot for the focus pathway
for (i in 1:3){
  pathway_name <- pathway_list$pathway[i]
  print(pathway_name)

  
  
  p<-plot_gsva_boxplot_4_group(gsva_matrix, 
                          condition_list_label =condition_list_label,
                          pathway_name =  pathway_name,
                          figure_folder = file.path(result_folder,"03-GSVA","Boxplot"),
                          file_name = paste0("GSVA_", pathway_name),
                          fig.height = 6, fig.width = 4,
                          save=FALSE,
                          group_1="CTRL+Veh", group_2="22q+Veh", 
                          group_3="CTRL+TTX", group_4="22q+TTX")
  print(p)
}


```



\newpage
# Session information
```{r}
sessionInfo()
```

