---
title: "Quality Control for bulk RNA-seq data"
author: "Ximing Ran"
date: "2025-02-28"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: false
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
hitheme: tomorrow
highlighter: highlight.js

---

```{r setup, include=FALSE}
# load libraries
library(tidyverse)
library(knitr)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 9,
  fig.height = 4,
  fig.path = "../results/01-QC/"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
knitr::kable(head(mtcars[, 1:4]), "simple")
```

```{r}
library(tibble)
library(tidyr)
library(dplyr)
library(rtracklayer)
```



```{r local_function_load}
# load function from local files
source(here::here("source", "plot_visit_line.R"))
source(here::here("source", "plot_regression.R"))
```

# 1. Read the count data     
```{r}

sample_list <- c(paste0("V", rep(1:10, each = 2), "-", 1:2), paste0("T", rep(1:10, each = 2), "-", 1:2))
condition_list <- c(rep("control", 10), rep("treated", 10))
counts_ref <- read.csv("../../2-mapping-result/bulkRNA/T1-1_final_gene_with_names.csv", header = TRUE)

counts <- tibble()
for (i in 1:length(sample_list)) {
  sample <- sample_list[i]
  gene_file <- paste0("../../2-mapping-result/bulkRNA/",sample, "_final_gene_with_names.csv")
  gene <- read.csv(gene_file, header = TRUE)
  
  if (i == 1) {
    counts <- gene[, c("GeneID", "GeneName")]
    counts <- counts %>% mutate(!!sample := gene$Count)
  } else {
    temp_counts <- gene[, c("GeneID", "Count")]
    colnames(temp_counts)[2] <- sample
    counts <- merge(counts, temp_counts, by = "GeneID")
  }
}

# replace all - in column names with _
colnames(counts) <- gsub("-", "_", colnames(counts))
write.csv(counts,"process_data/bulkRNA_counts.csv")

```




\newpage
```{r}
sessionInfo()
```

